export const QUERIES = {
  LINKED_APP: {
    LIST: 'LINKED_APP_LIST',
    OPTIONS: 'LINKED_APP_OPTIONS',
  },
  SETTING: {
    LOCAL_NETWORK: 'LOCAL_NETWORK',
    SYSTEM_INFO: 'SYSTEM_INFO',
    CONNECTOR: 'CONNECTOR',
    OPENPLATFORM: 'OPENPLATFORM',
    WEBCAM: 'WEBCAM',
  },
  ANALYSIS: {
    RESULT: 'RESULT',
    ALGORIGHM: 'ALGORIGHM',
  },
  ASSISTANT: {
    SENSOR: 'SENSOR',
  },
};
